### ISSUE TITLE
Eyetracker crashes when running Tobii_Scripts\g3pylib\examples

### ISSUE THREAD

**Issue by Z500-RAY** [tobiipro/g3pylib#93]
Initially, the program could run normally, outputting gaze points and videos, but after about 4~6 seconds, the program ends prematurely. The returned error message is as follows:

![cb0d8c7814948d8eae656361f709c91](https://github.com/tobiipro/g3pylib/assets/76550496/f838edf8-98f4-41e4-92ff-d6d93822783b)

As you can see, the error info here is None.

I want to know a more precise error feedback.

Considering that the computing load of the program might be too high and terminated by the system, I used task manager to check the running situation, and the results are as follows:

![image](https://github.com/tobiipro/g3pylib/assets/76550496/030fb829-24af-4fbe-aeda-6aa96526cd17)

![image](https://github.com/tobiipro/g3pylib/assets/76550496/5d8e18cb-29e5-4414-a902-55d304622bdb)

My memory size is 16G, and there is still 5G of surplus at this time. According to the feedback from the CPU, the crash should not be due to computer performance. I would like to know the possible reasons.

My computer configuration is:

- WIN10

- CPU:11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz

- GPU:Intel(R) UHD Graphics

**Comment by soderholmen** [comment]
I have the same issue, did you solve it?
