### ISSUE TITLE
How to use python to sent TTL to Glass3 to sync with EEG?

### ISSUE THREAD

**Issue by tenuosi** [tobiipro/g3pylib#95]
Hi!
I want to make Glass3 sync with EEG, but i don't know how to send the TTL to Glass3 by python, is there any example?

**Comment by jonashogstrom** [comment]
Glasses3 will send periodic sync events on the TTL out pin during a recording. For more details, see chapter 10 in the developer guide: https://go.tobii.com/tobii-pro-glasses-3-developer-guide
Glasses 3 will also record any TTL event that comes on the TTL in pin during a recording.

There is no support for sending TTL signals at custom intervals.
