### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ldt17** [tobiipro/g3pylib#96]
I encountered a problem during the installation process using "pip install .".

![image](https://github.com/tobiipro/g3pylib/assets/58940649/9deef23d-9ccb-42dd-a968-a5c51c534fcc)

By the way, may I ask if I need to install this SDK to process the data on the eye tracker Tobii Glasses 3？

Looking forward to your reply. Thank you！

**Comment by jonashogstrom** [comment]
It looks like your computer was not connected to the internet when you tried to install. The package has dependencies that needs to be downloaded from pypi.org.
You only need to install the library if you intend to interact with the Glasses 3 API from your own custom python code. If you only plan to record data using the Glasses 3 Controller software and analyze the recording afterwards, there is no need to install this python library.
